name: Auto-convert JSON Strategy Guides

on:
  push:
    paths:
      - 'data/*.json'
  pull_request:
    paths:
      - 'data/*.json'
  workflow_dispatch:

jobs:
  convert-json-guides:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Clean and convert JSON files
      run: |
        # First, clean JSON files of problematic characters
        python .github/scripts/fix_json_characters.py --data-dir --no-backup
        
        # Convert JSON files to Markdown guides
        python .github/scripts/json_to_markdown.py
        
        # Convert JSON files to checklists
        python .github/scripts/json_to_checklist.py
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files changed:"
          git status --porcelain
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add guides/ checklists/
        git commit -m "Auto-convert JSON guides to Markdown and checklists
        
        - Generated from JSON files in data/
        - Updated guides/ and checklists/ directories
        - Cross-linked guides and checklists"
        git push
